name: "Build NH"

on:
  pull_request:
  push:
    branches-ignore:
      - 'update-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: cachix/install-nix-action@master
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - run: nix build -L --no-link
        name: Build

      - run: |
          eval "$(nix print-dev-env)"
          ./fix.sh
          git diff-index --quiet HEAD
        name: Check formatting

  Test_Darwin:
    runs-on: macos-latest

    steps:
      - uses: cachix/install-nix-action@master
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - run: nix build -L --no-link
        name: Build

      - run: nix run -L .#nh -- darwin switch --hostname nh_test --dry .
        name: Test Switching to Nix Darwin Configuration
