name: "Build NH"

on:
  pull_request:
  push:
    branches-ignore:
      - 'update-*'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix build github:$GITHUB_REPOSITORY/$GITHUB_SHA --json | nix run nixpkgs#jq -- -r '.[].outputs | to_entries[].value' | nix run nixpkgs#cachix push toyvo
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

      # TODO: use the nixpkgs NixOS module or move test to nixpkgs
      # TODO: use unshare instead of sudo to mount
      # - name: NixOS check
      #   env:
      #     out: /nixos
      #   run: |
      #     sudo /bin/bash <<EOF
      #     source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      #     mkdir -pv $out
      #     mount -t tmpfs none $out
      #     nix profile install nixpkgs#nixos-install-tools
      #     nixos-install \
      #       --flake github:$GITHUB_REPOSITORY/$GITHUB_SHA#check \
      #       --root $out \
      #       --no-root-passwd \
      #       --no-bootloader
      #     EOF
